### PR TITLE
add cron yaml file 

### PR DESCRIPTION
**Pull request by sorinverescu**

### CODE REVIEW

**Comment by lazzurs** [comment]
Would this be a better way of doing this release?

https://github.com/release-drafter/release-drafter

**Comment by lazzurs** [comment]
Also please squish commits.

**Review by lazzurs — CHANGES_REQUESTED** [review]
Two changes requested.

**Comment by sorinverescu** [comment]
> Also please squish commits.

Commits squashed.

**Comment by sorinverescu** [comment]
> Would this be a better way of doing this release?
> 
> https://github.com/release-drafter/release-drafter

This is doing a release and then main.yaml file is picking up the work to build image and publish it. Should we still look into release-drafter ?

**Pull request merged**
